### ISSUE TITLE
TS化に伴う型注釈の改善2

### ISSUE THREAD

**Issue by swfz** [swfz/til#921]
- [x] Search系 -> #922 でリプレイスと合わせて改善
- [x] mocks #928
- [x] gatsby-browser.ts #924
- [x] gatsby-node.ts #925
- [x] gatsby-config.ts #920
- [x] __tests__ #919 #926
- [x] tsファイルをフォーマット対象に追加 #928
- [x] 型チェックをCIに追加 #930

**Comment by swfz** [comment]
残り

```
$ yarn typecheck | grep ' error TS'
gatsby-node.ts(68,17): error TS2571: Object is of type 'unknown'.
gatsby-node.ts(70,18): error TS7006: Parameter 'post' implicitly has an 'any' type.
gatsby-node.ts(70,24): error TS7006: Parameter 'index' implicitly has an 'any' type.
gatsby-node.ts(85,34): error TS7006: Parameter 'acc' implicitly has an 'any' type.
gatsby-node.ts(85,39): error TS7006: Parameter 'cur' implicitly has an 'any' type.
gatsby-node.ts(111,20): error TS2769: No overload matches this call.
gatsby-node.ts(129,16): error TS2571: Object is of type 'unknown'.
gatsby-node.ts(131,16): error TS7006: Parameter 'tag' implicitly has an 'any' type.
src/components/__tests__/archive.tsx(11,49): error TS2345: Argument of type '() => Date' is not assignable to parameter of type '() => string'.
src/components/__tests__/line.tsx(19,59): error TS2322: Type '{ frontmatter: { title: string; tags: string[]; date: string; }; fields: { slug: string; }; }' is not assignable to type 'MarkdownNode'.
src/components/__tests__/line.tsx(35,40): error TS2322: Type '{ frontmatter: { title: string; tags: string[]; date: string; }; fields: { slug: string; }; }' is not assignable to type 'MarkdownNode'.
src/mocks/handler.ts(2,22): error TS2307: Cannot find module './pixela.svg' or its corresponding type declarations.
src/mocks/handler.ts(4,22): error TS2732: Cannot find module './search-response2.json'. Consider using '--resolveJsonModule' to import module with '.json' extension.
error Command failed with exit code 2.
```
